// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "math/big"

const TableNameChecking = "checking"

// Checking mapped from table <checking>
type Checking struct {
	Number  int64     `gorm:"column:number;primaryKey" json:"number"`
	Charge  big.Float `gorm:"column:charge;not null" json:"charge"`
	Balance big.Float `gorm:"column:balance;not null;default:0.00" json:"balance"`
}

// TableName Checking's table name
func (*Checking) TableName() string {
	return TableNameChecking
}
