// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomer = "customer"

// Customer mapped from table <customer>
type Customer struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Fname    string `gorm:"column:fname;not null" json:"fname"`
	Lname    string `gorm:"column:lname;not null" json:"lname"`
	State    string `gorm:"column:state;not null" json:"state"`
	City     string `gorm:"column:city;not null" json:"city"`
	Zip      string `gorm:"column:zip;not null" json:"zip"`
	Address  string `gorm:"column:address;not null" json:"address"`
	Username string `gorm:"column:username" json:"username"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
