// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "math/big"

const TableNameLoan = "loan"

// Loan mapped from table <loan>
type Loan struct {
	Number  int64     `gorm:"column:number;primaryKey" json:"number"`
	Rate    big.Float `gorm:"column:rate;not null" json:"rate"`
	Amount  big.Float `gorm:"column:amount;not null" json:"amount"`
	Months  int32     `gorm:"column:months;not null" json:"months"`
	Payment big.Float `gorm:"column:payment;not null" json:"payment"`
	Type    string    `gorm:"column:type;not null" json:"type"`
}

// TableName Loan's table name
func (*Loan) TableName() string {
	return TableNameLoan
}
