// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLoanPayment = "loan_payment"

// LoanPayment mapped from table <loan_payment>
type LoanPayment struct {
	Number        int64     `gorm:"column:number;not null" json:"number"`
	PaymentDate   time.Time `gorm:"column:payment_date;not null" json:"payment_date"`
	PaymentAmount float64   `gorm:"column:payment_amount;not null" json:"payment_amount"`
	BalanceAfter  float64   `gorm:"column:balance_after;not null" json:"balance_after"`
}

// TableName LoanPayment's table name
func (*LoanPayment) TableName() string {
	return TableNameLoanPayment
}
