// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniversity = "university"

// StudentLoan mapped from table <student_loan>
type University struct {
	Id   int64  `gorm:"column:id;primaryKey" json:"id"`
	Name string `gorm:"Name;not null" json:"name"`
}

// TableName StudentLoan's table name
func (*University) TableName() string {
	return TableNameUniversity
}
