// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

//// User mapped from table <user>
type User struct {
	Username string `gorm:"column:username;primaryKey" form:"username" binding:"required,min=4,max=20" `
	Password string `gorm:"column:password;not null"  form:"password" binding:"required,min=4,max=20" `
	Role     string `gorm:"column:role;not null" form:"role"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
