#db:
#  host: 104.253.195.165
#  port: 3306
#  username: WD5JXYKyWK33zGjk
#  password: kX38p5rfnWkNtE5p
#  dbname: bank

db:
  host: 199.119.138.217
  port: 3306
  username: WD5JXYKyWK33zGjk
  password: kX38p5rfnWkNtE5p
  dbname: bank
